
-- 1. VAI TRO
CREATE TABLE VaiTro (
    MaVaiTro INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TenVaiTro VARCHAR(50) NOT NULL UNIQUE,
    MoTa VARCHAR(100)
);

-- 2. TAI KHOAN (Dung chung cho Authentication)
CREATE TABLE TaiKhoan (
    MaTaiKhoan INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Email VARCHAR(100) NOT NULL UNIQUE,
    MatKhauHash VARCHAR(255) NOT NULL,
    MaVaiTro INT NOT NULL,
    TrangThaiHoatDong BOOLEAN DEFAULT TRUE, -- TRUE: Hoat dong, FALSE: Khoa
    NgayTao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    NgayCapNhat TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (MaVaiTro) REFERENCES VaiTro(MaVaiTro)
);

-- 2. HO SO NHA TUYEN DUNG
-- Khong dung IDENTITY vi la quan he 1-1, lay ID tu TaiKhoan
CREATE TABLE NhaTuyenDung (
    MaNhaTuyenDung INT PRIMARY KEY,
    TenCongTy VARCHAR(150),
    SoDienThoai VARCHAR(20),
    Website VARCHAR(255),
    DiaChi VARCHAR(255),
    MoTa TEXT,
    Logo VARCHAR(500),
    AnhBia VARCHAR(500),
    FOREIGN KEY (MaNhaTuyenDung) REFERENCES TaiKhoan(MaTaiKhoan)
);

-- 3. HO SO UNG VIEN
-- Khong dung IDENTITY vi la quan he 1-1, lay ID tu TaiKhoan
CREATE TABLE UngVien (
    MaUngVien INT PRIMARY KEY,
    HoTen VARCHAR(100) NOT NULL,
    SoDienThoai VARCHAR(20) UNIQUE,
    LinkLinkedIn VARCHAR(255),
    ChucDanhHienTai VARCHAR(150),
    SoNamKinhNghiem INT DEFAULT 0,
    AnhDaiDien VARCHAR(500),
    GioiThieu TEXT,
    FOREIGN KEY (MaUngVien) REFERENCES TaiKhoan(MaTaiKhoan),
    CONSTRAINT CHK_UngVien_SoNamKN CHECK (SoNamKinhNghiem >= 0)
);

-- 4. DANH MUC KY NANG (Master Data)
CREATE TABLE DanhMucKyNang (
    MaKyNang INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TenKyNang VARCHAR(100) NOT NULL UNIQUE, -- VD: 'C#', 'ReactJS', 'SQL Server'
    PhanLoai VARCHAR(50) -- VD: 'Language', 'Framework', 'Database', 'SoftSkill'
);

-- 5. KY NANG CUA UNG VIEN (Mapping)
CREATE TABLE ChiTietKyNang_UngVien (
    MaUngVien INT,
    MaKyNang INT,
    SoNamKinhNghiem INT,
    PRIMARY KEY (MaUngVien, MaKyNang),
    FOREIGN KEY (MaUngVien) REFERENCES UngVien(MaUngVien),
    FOREIGN KEY (MaKyNang) REFERENCES DanhMucKyNang(MaKyNang)
);

-- 5.5 NGANH NGHE
CREATE TABLE NganhNghe (
    MaNganhNghe INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TenNganhNghe VARCHAR(100) NOT NULL UNIQUE,
    MoTa VARCHAR(255)
);

-- 6. TIN TUYEN DUNG (Job Description - JD)
CREATE TABLE TinTuyenDung (
    MaTin INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaNhaTuyenDung INT,
    FOREIGN KEY (MaNhaTuyenDung) REFERENCES NhaTuyenDung(MaNhaTuyenDung),
    MaNganhNghe INT,
    FOREIGN KEY (MaNganhNghe) REFERENCES NganhNghe(MaNganhNghe),
    TieuDe VARCHAR(200) NOT NULL,
    PhongBan VARCHAR(100),
    DiaDiem VARCHAR(200),
    HinhThucLamViec VARCHAR(50),
    MucLuongToiThieu DECIMAL(18,2),
    MucLuongToiDa DECIMAL(18,2),
    MoTaCongViec TEXT NOT NULL,
    YeuCauCongViec TEXT NOT NULL,
    QuyenLoi TEXT,
    SoLuongCanTuyen INT DEFAULT 1,
    SoLuongDaNop INT DEFAULT 0,
    TrangThai VARCHAR(50) DEFAULT 'DangMo',
    HanNopCV TIMESTAMP NOT NULL,
    DaXoa BOOLEAN DEFAULT FALSE,
    NgayTao TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    NgayCapNhat TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT CHK_TinTuyenDung_TrangThai CHECK (TrangThai IN ('DangMo', 'DaDong', 'DaHuy')),
    CONSTRAINT CHK_TinTuyenDung_HinhThuc CHECK (HinhThucLamViec IN ('FullTime', 'PartTime', 'Online', 'Intern')),
    CONSTRAINT CHK_TinTuyenDung_Luong CHECK (MucLuongToiThieu >= 0 AND MucLuongToiDa >= MucLuongToiThieu)
);
CREATE INDEX IX_TinTuyenDung_TrangThai_HanNop ON TinTuyenDung(TrangThai, HanNopCV);

-- 7. KY NANG YEU CAU CUA TIN TUYEN DUNG (Mapping)
CREATE TABLE ChiTietKyNang_TinTuyenDung (
    MaTin INT,
    MaKyNang INT,
    CapDoYeuCau VARCHAR(50) DEFAULT 'KhongBatBuoc', -- 'BatBuoc', 'UuTien', 'KhongBatBuoc'
    PRIMARY KEY (MaTin, MaKyNang),
    FOREIGN KEY (MaTin) REFERENCES TinTuyenDung(MaTin),
    FOREIGN KEY (MaKyNang) REFERENCES DanhMucKyNang(MaKyNang),
    CONSTRAINT CHK_ChiTietKyNang_CapDo CHECK (CapDoYeuCau IN ('BatBuoc', 'UuTien', 'KhongBatBuoc'))
);

-- 8. DON UNG TUYEN (Gop tu HoSoCV)
CREATE TABLE DonUngTuyen (
    MaDon INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaTin INT,
    FOREIGN KEY (MaTin) REFERENCES TinTuyenDung(MaTin),
    MaUngVien INT,
    FOREIGN KEY (MaUngVien) REFERENCES UngVien(MaUngVien),
    TenFile VARCHAR(255) NOT NULL,
    DuongDanFile VARCHAR(500) NOT NULL,
    DinhDang VARCHAR(20) NOT NULL,
    NoiDungTrichXuat TEXT,
    TrangThai VARCHAR(50) DEFAULT 'DaNop',
    NgayNop TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    NgayCapNhat TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT CHK_DonUngTuyen_TrangThai CHECK (TrangThai IN ('DaNop', 'AIDaLoc', 'DaChapNhan', 'PhongVan', 'TrungTuyen', 'TuChoi'))
);
-- Ngan 1 ung vien apply 1 job nhieu lan tai cung 1 thoi diem
CREATE UNIQUE INDEX UQ_DonUngTuyen_Tin_UngVien ON DonUngTuyen(MaTin, MaUngVien);

-- 10. KET QUA AI PHAN TICH
CREATE TABLE KetQua_AI (
    MaKetQua INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaDon INT,
    FOREIGN KEY (MaDon) REFERENCES DonUngTuyen(MaDon),
    TrangThaiXuLy VARCHAR(50) DEFAULT 'DangXuLy',
    DiemPhuHop DECIMAL(5,2),
    TomTatUngVien TEXT,
    KyNangPhuHop_Json TEXT,
    KyNangThieu_Json TEXT,
    DiemManh TEXT,
    DiemYeu TEXT,
    DeXuat VARCHAR(50),
    PhanHoiGocTuAI TEXT,
    NgayPhanTich TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT CHK_KetQuaAI_TrangThai CHECK (TrangThaiXuLy IN ('DangXuLy', 'HoanThanh', 'Loi')),
    CONSTRAINT CHK_KetQuaAI_DeXuat CHECK (DeXuat IN ('TuyenNhanh', 'CoTheCanNhac', 'LoaiBo'))
);
CREATE INDEX IX_KetQuaAI_DiemPhuHop ON KetQua_AI(DiemPhuHop DESC);

-- 11. INDEX BO SUNG DE TOI UU
CREATE INDEX IX_TinTuyenDung_NhaTuyenDung ON TinTuyenDung(MaNhaTuyenDung);
CREATE INDEX IX_DonUngTuyen_Tin_TrangThai ON DonUngTuyen(MaTin, TrangThai);
CREATE INDEX IX_DonUngTuyen_UngVien ON DonUngTuyen(MaUngVien);
CREATE INDEX IX_UngVien_HoTen ON UngVien(HoTen);
CREATE INDEX IX_TaiKhoan_VaiTro ON TaiKhoan(MaVaiTro);

-- 12. LICH HEN PHONG VAN
CREATE TABLE LichHenPhongVan (
    MaLichHen INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaDon INT,
    FOREIGN KEY (MaDon) REFERENCES DonUngTuyen(MaDon),
    NgayPhuongVan DATE NOT NULL,
    GioPhuongVan TIME NOT NULL,
    DiaDiem VARCHAR(255),
    LinkHop VARCHAR(500),
    HinhThuc VARCHAR(50) DEFAULT 'Online', -- 'Online', 'Offline'
    GhiChu TEXT,
    TrangThai VARCHAR(50) DEFAULT 'ChoXacNhan' NOT NULL,
    NgayTao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT CHK_LichHen_HinhThuc CHECK (HinhThuc IN ('Online', 'Offline')),
    CONSTRAINT CHK_LichHen_TrangThai CHECK (TrangThai IN ('ChoXacNhan', 'DaXacNhan', 'DaHuy', 'HoanThanh')),
    CONSTRAINT CHK_LichHen_DiaDiem_LinkHop CHECK (
        (HinhThuc = 'Online' AND LinkHop IS NOT NULL AND DiaDiem IS NULL) OR
        (HinhThuc = 'Offline' AND DiaDiem IS NOT NULL AND LinkHop IS NULL)
    )
);
CREATE INDEX IX_LichHen_MaDon ON LichHenPhongVan(MaDon);
CREATE INDEX IX_LichHen_Ngay ON LichHenPhongVan(NgayPhuongVan);


-- =========================================================================
-- SCRIPT MOCK DATA - SMART RECRUITER
-- (IDENTITY GENERATED BY DEFAULT: cho phep INSERT ID tuong minh)
-- =========================================================================

-- ---------------------------------------------------------
-- 0. VAI TRO
-- ---------------------------------------------------------

INSERT INTO VaiTro (MaVaiTro, TenVaiTro) VALUES
(1, 'Admin'),
(2, 'NhaTuyenDung'),
(3, 'UngVien');


-- ---------------------------------------------------------
-- 1. TAI KHOAN (2 Admin, 4 HR, 8 Ung vien)
-- ---------------------------------------------------------

INSERT INTO TaiKhoan (MaTaiKhoan, Email, MatKhauHash, MaVaiTro, TrangThaiHoatDong, NgayTao, NgayCapNhat) VALUES
-- Admins (ID: 1-2)
(1, 'admin1@smartrecruit.vn', '$2a$11$DFsfGKhBLo8Ez7W33DxuX.GGO/QGv1R48f16zqjgSSwrnRWRUgPl2', 1, TRUE, '2023-01-01 08:00', '2023-01-01 08:00'),
(2, 'admin2@smartrecruit.vn', '$2a$11$DFsfGKhBLo8Ez7W33DxuX.GGO/QGv1R48f16zqjgSSwrnRWRUgPl2', 1, TRUE, '2023-01-02 08:00', '2023-01-02 08:00'),
-- HRs (ID: 3-6)
(3, 'tuyendung@fpt.com.vn', '$2a$11$DFsfGKhBLo8Ez7W33DxuX.GGO/QGv1R48f16zqjgSSwrnRWRUgPl2', 2, TRUE, '2023-05-10 09:00', '2023-05-10 09:00'),
(4, 'hr.vng@vng.com.vn', '$2a$11$DFsfGKhBLo8Ez7W33DxuX.GGO/QGv1R48f16zqjgSSwrnRWRUgPl2', 2, TRUE, '2023-06-15 10:00', '2023-06-15 10:00'),
(5, 'recruitment@viettel.vn', '$2a$11$DFsfGKhBLo8Ez7W33DxuX.GGO/QGv1R48f16zqjgSSwrnRWRUgPl2', 2, TRUE, '2023-07-20 08:30', '2023-07-20 08:30'),
(6, 'hr@momo.vn', '$2a$11$DFsfGKhBLo8Ez7W33DxuX.GGO/QGv1R48f16zqjgSSwrnRWRUgPl2', 2, TRUE, '2023-08-05 14:00', '2023-08-05 14:00'),
-- Candidates (ID: 7-14)
(7, 'nguyenvana@gmail.com', '$2a$11$DFsfGKhBLo8Ez7W33DxuX.GGO/QGv1R48f16zqjgSSwrnRWRUgPl2', 3, TRUE, '2024-01-10 09:15', '2024-01-10 09:15'),
(8, 'tranthingoc@gmail.com', '$2a$11$DFsfGKhBLo8Ez7W33DxuX.GGO/QGv1R48f16zqjgSSwrnRWRUgPl2', 3, TRUE, '2024-01-12 10:20', '2024-01-12 10:20'),
(9, 'lehoanghai.dev@gmail.com', '$2a$11$DFsfGKhBLo8Ez7W33DxuX.GGO/QGv1R48f16zqjgSSwrnRWRUgPl2', 3, TRUE, '2024-02-05 14:00', '2024-02-05 14:00'),
(10, 'phamminhtuan@gmail.com', '$2a$11$DFsfGKhBLo8Ez7W33DxuX.GGO/QGv1R48f16zqjgSSwrnRWRUgPl2', 3, TRUE, '2024-02-20 16:45', '2024-02-20 16:45'),
(11, 'hoangthanhmai@gmail.com', '$2a$11$DFsfGKhBLo8Ez7W33DxuX.GGO/QGv1R48f16zqjgSSwrnRWRUgPl2', 3, TRUE, '2024-03-01 08:30', '2024-03-01 08:30'),
(12, 'vuminhduc.ai@gmail.com', '$2a$11$DFsfGKhBLo8Ez7W33DxuX.GGO/QGv1R48f16zqjgSSwrnRWRUgPl2', 3, TRUE, '2024-03-15 11:11', '2024-03-15 11:11'),
(13, 'doanvanhau.it@gmail.com', '$2a$11$DFsfGKhBLo8Ez7W33DxuX.GGO/QGv1R48f16zqjgSSwrnRWRUgPl2', 3, TRUE, '2024-03-20 09:00', '2024-03-20 09:00'),
(14, 'ngotienhiep@gmail.com', '$2a$11$DFsfGKhBLo8Ez7W33DxuX.GGO/QGv1R48f16zqjgSSwrnRWRUgPl2', 3, FALSE, '2024-04-01 10:00', '2024-04-05 10:00'); -- Bi khoa


-- ---------------------------------------------------------
-- 2. HO SO NHA TUYEN DUNG (Khong co IDENTITY, map ID: 3-6)
-- ---------------------------------------------------------
INSERT INTO NhaTuyenDung (MaNhaTuyenDung, TenCongTy, SoDienThoai, Website, DiaChi, MoTa, Logo) VALUES
(3, 'FPT Software', '0901111222', 'https://fptsoftware.com', 'Duy Tân, Cầu Giấy, Hà Nội', 'Công ty xuất khẩu phần mềm hàng đầu Việt Nam...', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6f9YQZ1I0v-t3zP8i_zY6N-V8u6RjXjP8wQ&s'),
(4, 'VNG Corporation', '0903333444', 'https://vng.com.vn', 'VNG Campus, Quận 7, TP.HCM', 'Kỳ lân công nghệ đầu tiên tại Việt Nam...', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzR6X-N1xR_m9QY_N_E-K8z1m_x_z_X1xR_g&s'),
(5, 'Viettel Group', '0988888999', 'https://viettel.vn', 'Giang Văn Minh, Ba Đình, Hà Nội', 'Tập đoàn Viễn thông và Công nghệ hàng đầu...', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR1-X1N1xR_m9QY_N_E-K8z1m_x_z_X1xR_g&s'),
(6, 'MoMo', '0912222333', 'https://momo.vn', 'Lầu 6, Phú Mỹ Hưng, Quận 7, TP.HCM', 'Ví điện tử số 1 Việt Nam...', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT3R6X-N1xR_m9QY_N_E-K8z1m_x_z_X1xR_g&s');

-- ---------------------------------------------------------
-- 3. HO SO UNG VIEN (Khong co IDENTITY, map ID: 7-14)
-- ---------------------------------------------------------
INSERT INTO UngVien (MaUngVien, HoTen, SoDienThoai, LinkLinkedIn, ChucDanhHienTai, SoNamKinhNghiem, AnhDaiDien, GioiThieu) VALUES
(7, 'Nguyễn Văn A', '0971112223', 'linkedin.com/in/nguyenvana', 'Backend .NET Developer', 4, '/avatars/uv7.jpg', 'Tôi là một lập trình viên .NET với 4 năm kinh nghiệm...'),
(8, 'Trần Thị Ngọc', '0972223334', 'linkedin.com/in/tranthingoc', 'Frontend ReactJS', 2, '/avatars/uv8.jpg', 'Yêu thích xây dựng giao diện người dùng hiện đại...'),
(9, 'Lê Hoàng Hải', '0973334445', 'linkedin.com/in/lehoanghai', 'Fullstack Developer', 5, '/avatars/uv9.jpg', 'Kinh nghiệm thực chiến với cả Backend và Frontend...'),
(10, 'Phạm Minh Tuấn', '0974445556', 'linkedin.com/in/phamminhtuan', 'Java Backend', 3, '/avatars/uv10.jpg', 'Chuyên gia về Java Spring Boot và Microservices...'),
(11, 'Hoàng Thanh Mai', '0975556667', 'linkedin.com/in/hoangthanhmai', 'Data Analyst', 2, '/avatars/uv11.jpg', 'Đam mê phân tích dữ liệu và đưa ra các insight...'),
(12, 'Vũ Minh Đức', '0976667778', 'linkedin.com/in/vuminhduc', 'AI Engineer', 4, '/avatars/uv12.jpg', 'Nghiên cứu và triển khai các mô hình Machine Learning...'),
(13, 'Đoàn Văn Hậu', '0977778889', 'linkedin.com/in/doanvanhau', 'DevOps Engineer', 3, '/avatars/uv13.jpg', 'Tối ưu hóa quy trình triển khai phần mềm...'),
(14, 'Ngô Tiến Hiệp', '0978889990', '', 'Fresher Web', 0, '/avatars/uv14.jpg', 'Sinh viên mới tốt nghiệp, ham học hỏi...');

-- ---------------------------------------------------------
-- 4. DANH MUC KY NANG (15 Ky nang)
-- ---------------------------------------------------------

INSERT INTO DanhMucKyNang (MaKyNang, TenKyNang, PhanLoai) VALUES
(1, 'C#', 'Language'),
(2, 'ASP.NET Core', 'Framework'),
(3, 'SQL Server', 'Database'),
(4, 'Java', 'Language'),
(5, 'Spring Boot', 'Framework'),
(6, 'ReactJS', 'Framework'),
(7, 'JavaScript', 'Language'),
(8, 'TypeScript', 'Language'),
(9, 'Python', 'Language'),
(10, 'Machine Learning', 'AI'),
(11, 'Docker', 'DevOps'),
(12, 'Kubernetes', 'DevOps'),
(13, 'AWS', 'Cloud'),
(14, 'Agile/Scrum', 'SoftSkill'),
(15, 'English', 'Language');


-- ---------------------------------------------------------
-- 5. KY NANG CUA UNG VIEN
-- ---------------------------------------------------------
INSERT INTO ChiTietKyNang_UngVien (MaUngVien, MaKyNang, SoNamKinhNghiem) VALUES
(7, 1, 4), (7, 2, 4), (7, 3, 3), (7, 14, 2), -- UV 7: .NET (4 nam)
(8, 6, 2), (8, 7, 2), (8, 8, 1),             -- UV 8: React (2 nam)
(9, 1, 5), (9, 2, 5), (9, 6, 3), (9, 11, 2), -- UV 9: Fullstack .NET + React (5 nam)
(10, 4, 3), (10, 5, 3), (10, 3, 2),          -- UV 10: Java (3 nam)
(12, 9, 4), (12, 10, 3), (12, 13, 2),        -- UV 12: AI/Python (4 nam)
(13, 11, 3), (13, 12, 2), (13, 13, 3);       -- UV 13: DevOps (3 nam)

-- ---------------------------------------------------------
-- 6. TIN TUYEN DUNG (6 Jobs)
-- Rang buoc: TrangThai (DangMo, DaDong, DaHuy), HinhThuc (FullTime, PartTime, Online, Intern)
-- ---------------------------------------------------------

-- ---------------------------------------------------------
-- 5.5 MOCK DATA NGANH NGHE
-- ---------------------------------------------------------
INSERT INTO NganhNghe (MaNganhNghe, TenNganhNghe, MoTa) VALUES
(1, 'IT - Phần mềm', 'Phát triển phần mềm, ứng dụng, hệ thống...'),
(2, 'IT - Phần cứng / Mạng', 'Quản trị mạng, DevOps, System Admin...'),
(3, 'Marketing / PR', 'Digital Marketing, PR, Thương hiệu...'),
(4, 'Thiết kế / Mỹ thuật', 'UI/UX Design, Đồ họa, Video Editor...'),
(5, 'Kế toán / Kiểm toán', 'Kế toán tổng hợp, Kiểm toán viên...'),
(6, 'Tài chính / Ngân hàng', 'Chuyên viên tài chính, Giao dịch viên...'),
(7, 'Nhân sự (HR)', 'Tuyển dụng, Đào tạo, C&B...');

INSERT INTO TinTuyenDung (MaTin, MaNhaTuyenDung, MaNganhNghe, TieuDe, PhongBan, DiaDiem, HinhThucLamViec, MucLuongToiThieu, MucLuongToiDa, MoTaCongViec, YeuCauCongViec, QuyenLoi, SoLuongCanTuyen, SoLuongDaNop, TrangThai, HanNopCV, DaXoa, NgayTao, NgayCapNhat) VALUES
(1, 3, 1, 'Senior .NET Developer', 'FSU1', 'Hà Nội', 'FullTime', 30000000, 50000000, 'Phát triển core banking...', 'Ít nhất 4 năm C#, ASP.NET Core', 'Lương tháng 13, BHYT', 5, 2, 'DangMo', '2026-12-31', FALSE, '2024-04-01 08:00', '2026-04-01 08:00'),
(2, 4, 1, 'Frontend ReactJS (Middle)', 'ZaloPay', 'TP.HCM', 'FullTime', 20000000, 35000000, 'Làm UI/UX cho ví điện tử...', 'Tối thiểu 2 năm ReactJS, Redux, TS', 'Ăn trưa miễn phí', 3, 2, 'DangMo', '2026-11-30', FALSE, '2026-04-05 09:00', '2026-04-05 09:00'),
(3, 5, 1, 'Java Backend Engineer', 'Viettel Digital', 'Hà Nội', 'FullTime', 25000000, 45000000, 'Xây dựng hệ thống High availability', 'Có kinh nghiệm Spring Boot, Microservices', 'Thưởng dự án', 10, 2, 'DangMo', '2026-10-15', FALSE, '2026-04-10 10:00', '2026-04-10 10:00'),
(4, 6, 1, 'AI / Machine Learning Engineer', 'Data Team', 'TP.HCM', 'FullTime', 40000000, 70000000, 'Xây dựng model recommend...', 'Thành thạo Python, Tensorflow/PyTorch', 'Cấp Macbook Pro', 2, 1, 'DangMo', '2026-06-01', FALSE, '2026-04-15 11:00', '2026-04-15 11:00'),
(5, 3, 1, 'Fresher .NET', 'FSU2', 'Đà Nẵng', 'Intern', 5000000, 10000000, 'Đào tạo từ đầu', 'Biết cơ bản C#', 'Được mentor kèm cặp', 10, 0, 'DaDong', '2026-03-30', FALSE, '2026-02-01 08:00', '2026-03-30 23:59'),
(6, 4, 2, 'Remote DevOps Engineer', 'Cloud Team', 'Toàn quốc', 'Online', 35000000, 55000000, 'Quản lý hệ thống AWS', 'Cứng Docker, K8s, AWS', 'Làm việc tại nhà', 1, 0, 'DaDong', '2026-12-31', TRUE, '2026-04-20 08:00', '2026-04-22 09:00');


-- ---------------------------------------------------------
-- 7. KY NANG YEU CAU CUA TIN TUYEN DUNG
-- Rang buoc: CapDoYeuCau (BatBuoc, UuTien, KhongBatBuoc)
-- ---------------------------------------------------------
INSERT INTO ChiTietKyNang_TinTuyenDung (MaTin, MaKyNang, CapDoYeuCau) VALUES
-- Job 1: .NET
(1, 1, 'BatBuoc'), (1, 2, 'BatBuoc'), (1, 3, 'BatBuoc'), (1, 14, 'UuTien'),
-- Job 2: React
(2, 6, 'BatBuoc'), (2, 7, 'BatBuoc'), (2, 8, 'UuTien'),
-- Job 3: Java
(3, 4, 'BatBuoc'), (3, 5, 'BatBuoc'), (3, 3, 'UuTien'),
-- Job 4: AI
(4, 9, 'BatBuoc'), (4, 10, 'BatBuoc'), (4, 15, 'UuTien'),
-- Job 5: Fresher .NET
(5, 1, 'BatBuoc'), (5, 3, 'KhongBatBuoc'),
-- Job 6: DevOps
(6, 11, 'BatBuoc'), (6, 12, 'BatBuoc'), (6, 13, 'BatBuoc');

-- ---------------------------------------------------------
-- 8. DON UNG TUYEN
-- Rang buoc: TrangThai (DaNop, AIDaLoc, TrungTuyen, TuChoi)
-- ---------------------------------------------------------

INSERT INTO DonUngTuyen (MaDon, MaTin, MaUngVien, TenFile, DuongDanFile, DinhDang, NoiDungTrichXuat, TrangThai, NgayNop, NgayCapNhat) VALUES
-- Job 1 (Senior .NET): UV 7 & UV 9 apply
(1, 1, 7, 'NguyenVanA_NET_CV.pdf', '/cvs/nguyenvana_1.pdf', 'PDF', 'Senior Backend .NET. Kỹ năng: C#, ASP.NET Core, SQL. 4 năm KN.', 'TrungTuyen', '2024-04-10 08:30', '2024-04-15 10:00'), -- UV7 pass
(2, 1, 9, 'LeHoangHai_Fullstack.docx', '/cvs/lehoanghai.docx', 'DOCX', 'Lập trình viên Fullstack. Backend .NET Core 5 năm, Frontend ReactJS 3 năm. Biết dùng Docker.', 'AIDaLoc', '2024-04-11 09:00', '2024-04-11 09:05'),   -- UV9 dang cho HR xem

-- Job 2 (ReactJS): UV 8 & UV 9 apply
(3, 2, 8, 'TranNgoc_ReactJS.pdf', '/cvs/tranngoc.pdf', 'PDF', 'Frontend React Developer. Có kinh nghiệm với ReactJS, JS, HTML/CSS.', 'AIDaLoc', '2024-04-12 10:00', '2024-04-12 10:05'),   -- UV8
(4, 2, 9, 'LeHoangHai_Fullstack.docx', '/cvs/lehoanghai.docx', 'DOCX', 'Lập trình viên Fullstack. Backend .NET Core 5 năm, Frontend ReactJS 3 năm. Biết dùng Docker.', 'DaNop', '2024-04-13 14:00', '2024-04-13 14:00'),     -- UV9 vua nop, AI chua chay xong

-- Job 3 (Java): UV 10 apply, UV 8 nop nham
(5, 3, 10, 'PhamTuan_Java.pdf', '/cvs/phamtuan.pdf', 'PDF', 'Java Dev. Tech stack: Java, Spring Boot, MySQL. 3 years experience.', 'TrungTuyen', '2024-04-14 09:00', '2024-04-20 16:00'), -- UV10 pass
(6, 3, 8, 'TranNgoc_ReactJS.pdf', '/cvs/tranngoc.pdf', 'PDF', 'Frontend React Developer. Có kinh nghiệm với ReactJS, JS, HTML/CSS.', 'TuChoi', '2024-04-15 10:00', '2024-04-15 10:10'),    -- UV8 tach vi sai skill

-- Job 4 (AI): UV 12 apply
(7, 4, 12, 'VuMinhDuc_AI.pdf', '/cvs/vuminhduc.pdf', 'PDF', 'AI/ML Engineer. Python, PyTorch, Scikit-learn. NLP projects.', 'AIDaLoc', '2024-04-16 11:00', '2024-04-16 11:05');    -- UV12



-- ---------------------------------------------------------
-- 10. KET QUA AI PHAN TICH
-- Rang buoc: TrangThaiXuLy (DangXuLy, HoanThanh, Loi), DeXuat (TuyenNhanh, CoTheCanNhac, LoaiBo)
-- ---------------------------------------------------------

INSERT INTO KetQua_AI (MaKetQua, MaDon, TrangThaiXuLy, DiemPhuHop, TomTatUngVien, KyNangPhuHop_Json, KyNangThieu_Json, DiemManh, DiemYeu, DeXuat, PhanHoiGocTuAI, NgayPhanTich) VALUES

-- MaDon 1 (UV7 -> Job .NET)
(1, 1, 'HoanThanh', 96.50,
'Ứng viên hoàn hảo cho vị trí Senior .NET. Có đủ 4 năm kinh nghiệm.',
'["C#", "ASP.NET Core", "SQL Server"]', '[]',
'Nền tảng .NET vững vàng.', 'Chưa thấy bằng cấp tiếng Anh.', 'TuyenNhanh', '{"status":"success"}', '2024-04-10 08:31'),

-- MaDon 2 (UV9 -> Job .NET)
(2, 2, 'HoanThanh', 90.00,
'Ứng viên Fullstack, kỹ năng .NET Core rất tốt (5 năm).',
'["C#", "ASP.NET Core"]', '["SQL Server"]',
'Biết cả Docker là điểm cộng.', 'CV ghi chung chung phần DB.', 'TuyenNhanh', '{"status":"success"}', '2024-04-11 09:02'),

-- MaDon 3 (UV8 -> Job React)
(3, 3, 'HoanThanh', 82.00,
'Ứng viên Middle Frontend, đáp ứng đủ yêu cầu cốt lõi.',
'["ReactJS", "JavaScript"]', '["TypeScript"]',
'Kinh nghiệm thực chiến 2 năm.', 'Thiếu TypeScript theo yêu cầu ưu tiên.', 'CoTheCanNhac', '{"status":"success"}', '2024-04-12 10:02'),

-- MaDon 4 (UV9 -> Job React) - AI DANG XU LY (Nen DiemPhuHop = NULL)
(4, 4, 'DangXuLy', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2024-04-13 14:00'),

-- MaDon 5 (UV10 -> Job Java)
(5, 5, 'HoanThanh', 92.00,
'Ứng viên chuyên Java Backend, kinh nghiệm khớp với JD.',
'["Java", "Spring Boot"]', '[]',
'Kinh nghiệm 3 năm chuẩn chỉ.', 'Không có.', 'TuyenNhanh', '{"status":"success"}', '2024-04-14 09:03'),

-- MaDon 6 (UV8 -> Job Java - Rot)
(6, 6, 'HoanThanh', 10.00,
'Ứng viên làm ReactJS, ứng tuyển nhầm vị trí Java Backend.',
'[]', '["Java", "Spring Boot"]',
'Không có.', 'Sai hoàn toàn định hướng chuyên môn.', 'LoaiBo', '{"status":"success"}', '2024-04-15 10:02'),

-- MaDon 7 (UV12 -> Job AI)
(7, 7, 'HoanThanh', 95.00,
'AI Engineer với kinh nghiệm Python và PyTorch mạnh.',
'["Python", "Machine Learning"]', '[]',
'Có project NLP thực tế.', 'Chưa rõ kỹ năng deploy model.', 'TuyenNhanh', '{"status":"success"}', '2024-04-16 11:03');



--=================================================
--==================================================

-- =========================================================================
-- SCRIPT MO RONG DU LIEU - SMART RECRUITER (PHAN 2)
-- =========================================================================

-- ---------------------------------------------------------
-- 1. THEM TAI KHOAN MOI (6 HR, 15 Ung vien)
-- Tiep noi ID tu 15 den 35
-- ---------------------------------------------------------

INSERT INTO TaiKhoan (MaTaiKhoan, Email, MatKhauHash, MaVaiTro, TrangThaiHoatDong, NgayTao) VALUES
-- HRs moi (ID: 15-20)
(15, 'hr@shopee.vn', '$2a$11$DFsfGKhBLo8Ez7W33DxuX.GGO/QGv1R48f16zqjgSSwrnRWRUgPl2', 2, TRUE, '2024-05-01 08:00'),
(16, 'tuyendung@tiki.vn', '$2a$11$DFsfGKhBLo8Ez7W33DxuX.GGO/QGv1R48f16zqjgSSwrnRWRUgPl2', 2, TRUE, '2024-05-02 08:00'),
(17, 'talent@vnpay.vn', '$2a$11$DFsfGKhBLo8Ez7W33DxuX.GGO/QGv1R48f16zqjgSSwrnRWRUgPl2', 2, TRUE, '2024-05-03 08:00'),
(18, 'hr@nashtech.com', '$2a$11$DFsfGKhBLo8Ez7W33DxuX.GGO/QGv1R48f16zqjgSSwrnRWRUgPl2', 2, TRUE, '2024-05-04 08:00'),
(19, 'recruitment@katalon.com', '$2a$11$DFsfGKhBLo8Ez7W33DxuX.GGO/QGv1R48f16zqjgSSwrnRWRUgPl2', 2, TRUE, '2024-05-05 08:00'),
(20, 'careers@vinai.io', '$2a$11$DFsfGKhBLo8Ez7W33DxuX.GGO/QGv1R48f16zqjgSSwrnRWRUgPl2', 2, TRUE, '2024-05-06 08:00'),

-- Candidates moi (ID: 21-35)
(21, 'lethanh.ba@gmail.com', '$2a$11$DFsfGKhBLo8Ez7W33DxuX.GGO/QGv1R48f16zqjgSSwrnRWRUgPl2', 3, TRUE, '2024-06-01 09:00'),
(22, 'tranquoctoan.qa@gmail.com', '$2a$11$DFsfGKhBLo8Ez7W33DxuX.GGO/QGv1R48f16zqjgSSwrnRWRUgPl2', 3, TRUE, '2024-06-02 10:00'),
(23, 'nguyenha.mobile@gmail.com', '$2a$11$DFsfGKhBLo8Ez7W33DxuX.GGO/QGv1R48f16zqjgSSwrnRWRUgPl2', 3, TRUE, '2024-06-03 11:00'),
(24, 'phamhung.ios@gmail.com', '$2a$11$DFsfGKhBLo8Ez7W33DxuX.GGO/QGv1R48f16zqjgSSwrnRWRUgPl2', 3, TRUE, '2024-06-04 14:00'),
(25, 'dovan.data@gmail.com', '$2a$11$DFsfGKhBLo8Ez7W33DxuX.GGO/QGv1R48f16zqjgSSwrnRWRUgPl2', 3, TRUE, '2024-06-05 15:00'),
(26, 'lynhan.uxui@gmail.com', '$2a$11$DFsfGKhBLo8Ez7W33DxuX.GGO/QGv1R48f16zqjgSSwrnRWRUgPl2', 3, TRUE, '2024-06-06 16:00'),
(27, 'vuongdinh.php@gmail.com', '$2a$11$DFsfGKhBLo8Ez7W33DxuX.GGO/QGv1R48f16zqjgSSwrnRWRUgPl2', 3, TRUE, '2024-06-07 09:30'),
(28, 'caothang.go@gmail.com', '$2a$11$DFsfGKhBLo8Ez7W33DxuX.GGO/QGv1R48f16zqjgSSwrnRWRUgPl2', 3, TRUE, '2024-06-08 10:30'),
(29, 'dinhbao.vue@gmail.com', '$2a$11$DFsfGKhBLo8Ez7W33DxuX.GGO/QGv1R48f16zqjgSSwrnRWRUgPl2', 3, TRUE, '2024-06-09 11:30'),
(30, 'truonggiang.ruby@gmail.com', '$2a$11$DFsfGKhBLo8Ez7W33DxuX.GGO/QGv1R48f16zqjgSSwrnRWRUgPl2', 3, TRUE, '2024-06-10 14:30'),
(31, 'ngocmai.tester@gmail.com', '$2a$11$DFsfGKhBLo8Ez7W33DxuX.GGO/QGv1R48f16zqjgSSwrnRWRUgPl2', 3, TRUE, '2024-06-11 15:30'),
(32, 'hoangnam.sysadmin@gmail.com', '$2a$11$DFsfGKhBLo8Ez7W33DxuX.GGO/QGv1R48f16zqjgSSwrnRWRUgPl2', 3, TRUE, '2024-06-12 16:30'),
(33, 'tuananh.fullstack@gmail.com', '$2a$11$DFsfGKhBLo8Ez7W33DxuX.GGO/QGv1R48f16zqjgSSwrnRWRUgPl2', 3, TRUE, '2024-06-13 09:00'),
(34, 'minhthu.marketing@gmail.com', '$2a$11$DFsfGKhBLo8Ez7W33DxuX.GGO/QGv1R48f16zqjgSSwrnRWRUgPl2', 3, TRUE, '2024-06-14 10:00'),
(35, 'bichtram.hr@gmail.com', '$2a$11$DFsfGKhBLo8Ez7W33DxuX.GGO/QGv1R48f16zqjgSSwrnRWRUgPl2', 3, TRUE, '2024-06-15 11:00');


-- ---------------------------------------------------------
-- 2. HO SO NHA TUYEN DUNG MOI
-- ---------------------------------------------------------
INSERT INTO NhaTuyenDung (MaNhaTuyenDung, TenCongTy, SoDienThoai, Website, DiaChi, MoTa, Logo) VALUES
(15, 'Shopee Vietnam', '0911223344', 'https://shopee.vn', 'Capital Place, Liễu Giai, Hà Nội', 'Nền tảng thương mại điện tử lớn nhất...', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4R6X-N1xR_m9QY_N_E-K8z1m_x_z_X1xR_g&s'),
(16, 'Tiki', '0922334455', 'https://tiki.vn', 'Phổ Quang, Tân Bình, TP.HCM', 'Sàn thương mại điện tử uy tín...', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT5R6X-N1xR_m9QY_N_E-K8z1m_x_z_X1xR_g&s'),
(17, 'VNPay', '0933445566', 'https://vnpay.vn', 'Láng Hạ, Đống Đa, Hà Nội', 'Giải pháp thanh toán điện tử...', NULL),
(18, 'NashTech', '0944556677', 'https://nashtechglobal.com', 'Etown, Tân Bình, TP.HCM', 'Tư vấn và giải pháp công nghệ...', NULL),
(19, 'Katalon', '0955667788', 'https://katalon.com', 'Quận 4, TP.HCM', 'Nền tảng kiểm thử tự động...', NULL),
(20, 'VinAI', '0966778899', 'https://vinai.io', 'Times City, Hai Bà Trưng, Hà Nội', 'Viện nghiên cứu trí tuệ nhân tạo...', NULL);

-- ---------------------------------------------------------
-- 3. HO SO UNG VIEN MOI
-- ---------------------------------------------------------
INSERT INTO UngVien (MaUngVien, HoTen, SoDienThoai, LinkLinkedIn, ChucDanhHienTai, SoNamKinhNghiem, AnhDaiDien, GioiThieu) VALUES
(21, 'Lê Thanh', '0811112222', 'linkedin.com/in/lethanh-ba', 'Senior Business Analyst', 5, NULL, 'Chuyên viên phân tích nghiệp vụ cao cấp...'),
(22, 'Trần Quốc Toản', '0822223333', 'linkedin.com/in/toantq', 'QA/QC Engineer', 3, NULL, 'Đảm bảo chất lượng sản phẩm phần mềm...'),
(23, 'Nguyễn Hà', '0833334444', 'linkedin.com/in/nguyenha-android', 'Android Developer', 4, NULL, 'Lập trình viên di động Android...'),
(24, 'Phạm Hùng', '0844445555', 'linkedin.com/in/phamhung-ios', 'iOS Developer', 2, NULL, 'Lập trình viên di động iOS...'),
(25, 'Đỗ Văn', '0855556666', 'linkedin.com/in/dovan-data', 'Data Engineer', 4, NULL, 'Kỹ sư dữ liệu với kinh nghiệm AWS...'),
(26, 'Lý Nhân', '0866667777', 'linkedin.com/in/lynhan-design', 'UI/UX Designer', 3, NULL, 'Thiết kế trải nghiệm người dùng...'),
(27, 'Vương Đình', '0877778888', 'linkedin.com/in/vuongdinh', 'PHP Developer', 5, NULL, 'Chuyên gia PHP và Laravel...'),
(28, 'Cao Thắng', '0888889999', 'linkedin.com/in/caothang', 'Golang Developer', 3, NULL, 'Lập trình viên Golang hiệu năng cao...'),
(29, 'Đinh Bảo', '0899990000', 'linkedin.com/in/dinhbao', 'Frontend VueJS', 2, NULL, 'Lập trình viên Frontend với VueJS...'),
(30, 'Trường Giang', '0900001111', 'linkedin.com/in/truonggiang', 'Ruby on Rails Dev', 4, NULL, 'Lập trình viên Ruby on Rails...'),
(31, 'Ngọc Mai', '0911110000', 'linkedin.com/in/ngocmai', 'Manual Tester', 1, NULL, 'Kiểm thử viên thủ công...'),
(32, 'Hoàng Nam', '0922221111', 'linkedin.com/in/hoangnam', 'System Admin', 6, NULL, 'Quản trị hệ thống và mạng...'),
(33, 'Tuấn Anh', '0933332222', 'linkedin.com/in/tuananh', 'Fullstack MERN', 3, NULL, 'Lập trình viên Fullstack MERN...'),
(34, 'Minh Thư', '0944443333', '', 'Digital Marketing', 2, NULL, 'Chuyên viên tiếp thị kỹ thuật số...'),
(35, 'Bích Trâm', '0955554444', '', 'HR Executive', 3, NULL, 'Chuyên viên nhân sự tổng hợp...');

-- ---------------------------------------------------------
-- 4. BO SUNG DANH MUC KY NANG (Them 20 Ky nang)
-- ID tiep noi tu 16 den 35
-- ---------------------------------------------------------

INSERT INTO DanhMucKyNang (MaKyNang, TenKyNang, PhanLoai) VALUES
(16, 'PHP', 'Language'), (17, 'Laravel', 'Framework'),
(18, 'Golang', 'Language'), (19, 'Ruby on Rails', 'Framework'),
(20, 'VueJS', 'Framework'), (21, 'Angular', 'Framework'),
(22, 'Swift', 'Language'), (23, 'Kotlin', 'Language'),
(24, 'Flutter', 'Framework'), (25, 'React Native', 'Framework'),
(26, 'MySQL', 'Database'), (27, 'PostgreSQL', 'Database'),
(28, 'MongoDB', 'Database'), (29, 'Redis', 'Database'),
(30, 'Figma', 'Tool'), (31, 'Selenium', 'Tool'),
(32, 'Appium', 'Tool'), (33, 'Business Analysis', 'SoftSkill'),
(34, 'UML', 'Tool'), (35, 'Linux', 'DevOps');


-- ---------------------------------------------------------
-- 5. KY NANG CUA UNG VIEN MOI
-- ---------------------------------------------------------
INSERT INTO ChiTietKyNang_UngVien (MaUngVien, MaKyNang, SoNamKinhNghiem) VALUES
(21, 33, 5), (21, 34, 4), (21, 14, 3), -- BA
(22, 31, 3), (22, 32, 2), (22, 26, 3), -- QA
(23, 23, 4), (23, 24, 2), (23, 11, 1), -- Android/Flutter
(24, 22, 2), (24, 25, 1),              -- iOS/React Native
(25, 9, 4), (25, 27, 4), (25, 13, 2),  -- Data (Python, Postgres, AWS)
(26, 30, 3), (26, 7, 1),               -- UI/UX (Figma, JS)
(27, 16, 5), (27, 17, 4), (27, 26, 5), -- PHP/Laravel
(28, 18, 3), (28, 11, 2), (28, 29, 2), -- Golang/Redis
(29, 20, 2), (29, 7, 2),               -- VueJS
(33, 28, 3), (33, 6, 3), (33, 7, 3);   -- MERN Stack (MongoDB, React, JS)

-- ---------------------------------------------------------
-- 6. THEM TIN TUYEN DUNG MOI (10 Jobs)
-- Tiep noi ID tu 7 den 16
-- ---------------------------------------------------------

INSERT INTO TinTuyenDung (MaTin, MaNhaTuyenDung, MaNganhNghe, TieuDe, PhongBan, DiaDiem, HinhThucLamViec, MucLuongToiThieu, MucLuongToiDa, MoTaCongViec, YeuCauCongViec, QuyenLoi, SoLuongCanTuyen, SoLuongDaNop, TrangThai, HanNopCV) VALUES
(7, 15, 1, 'Senior Golang Developer', 'Backend', 'TP.HCM', 'FullTime', 40000000, 60000000, 'Xây dựng core system e-commerce', '3+ năm Golang, Microservices, Redis', 'Thưởng cổ phiếu', 2, 2, 'DangMo', '2026-12-31'),
(8, 16, 1, 'PHP/Laravel Dev', 'Product', 'Hà Nội', 'FullTime', 15000000, 25000000, 'Bảo trì hệ thống ERP nội bộ', '2 năm PHP Laravel, MySQL', 'BHXH full lương', 1, 1, 'DangMo', '2024-10-30'),
(9, 17, 1, 'Mobile Dev (Flutter)', 'Mobile App', 'Hà Nội', 'FullTime', 20000000, 35000000, 'Làm app ví điện tử', 'Thành thạo Flutter, biết Native là lợi thế', 'Môi trường trẻ trung', 3, 1, 'DangMo', '2026-11-15'),
(10, 18, 1, 'QA Automation Engineer', 'Testing', 'Đà Nẵng', 'FullTime', 18000000, 28000000, 'Viết script auto test cho Web & App', 'Selenium, Appium, Java/Python', 'Làm việc với khách Âu', 4, 1, 'DangMo', '2026-12-01'),
(11, 19, 1, 'Senior Business Analyst', 'Consulting', 'TP.HCM', 'FullTime', 30000000, 45000000, 'Lấy yêu cầu khách hàng, vẽ flow', 'Kinh nghiệm BA 4 năm+, UML, SQL', 'Cơ hội Onsite', 1, 1, 'DangMo', '2026-11-20'),
(12, 20, 1, 'Data Engineer', 'Data Lab', 'Hà Nội', 'FullTime', 35000000, 55000000, 'Xây dựng Data Warehouse', 'Python, Postgres, AWS/GCP', 'Chế độ chuyên gia', 2, 2, 'DangMo', '2024-12-31'),
(13, 15, 4, 'UI/UX Designer', 'Design Team', 'TP.HCM', 'FullTime', 15000000, 25000000, 'Thiết kế giao diện App, Web', 'Thành thạo Figma, tư duy UX tốt', 'Cấp Mac Studio', 1, 1, 'DangMo', '2026-10-10'),
(14, 16, 1, 'VueJS Frontend Dev', 'Storefront', 'Toàn quốc', 'Online', 18000000, 30000000, 'Phát triển trang bán hàng', 'Kinh nghiệm VueJS 2 năm+', 'Remote linh hoạt', 3, 2, 'DangMo', '2026-11-11'),
(15, 17, 1, 'iOS Developer (Fresher)', 'Mobile App', 'Hà Nội', 'Intern', 5000000, 8000000, 'Học việc iOS', 'Nắm vững Swift cơ bản', 'Trợ cấp thực tập', 2, 1, 'DaDong', '2026-05-30'),
(16, 18, 2, 'System Administrator', 'IT Helpdesk', 'TP.HCM', 'FullTime', 20000000, 30000000, 'Quản trị server, mạng nội bộ', 'Linux, Windows Server, Network', 'Bảo hiểm PVI', 1, 0, 'DaDong', '2026-06-01');


-- ---------------------------------------------------------
-- 7. KY NANG YEU CAU CUA TIN TUYEN DUNG MOI
-- ---------------------------------------------------------
INSERT INTO ChiTietKyNang_TinTuyenDung (MaTin, MaKyNang, CapDoYeuCau) VALUES
-- Job 7: Golang
(7, 18, 'BatBuoc'), (7, 29, 'BatBuoc'), (7, 11, 'UuTien'),
-- Job 8: PHP
(8, 16, 'BatBuoc'), (8, 17, 'BatBuoc'), (8, 26, 'BatBuoc'),
-- Job 9: Mobile Flutter
(9, 24, 'BatBuoc'), (9, 22, 'UuTien'), (9, 23, 'UuTien'),
-- Job 10: QA
(10, 31, 'BatBuoc'), (10, 32, 'UuTien'), (10, 4, 'KhongBatBuoc'),
-- Job 11: BA
(11, 33, 'BatBuoc'), (11, 34, 'BatBuoc'), (11, 3, 'UuTien'),
-- Job 12: Data Engineer
(12, 9, 'BatBuoc'), (12, 27, 'BatBuoc'), (12, 13, 'BatBuoc'),
-- Job 13: UI/UX
(13, 30, 'BatBuoc'), (13, 7, 'KhongBatBuoc'),
-- Job 14: VueJS
(14, 20, 'BatBuoc'), (14, 7, 'BatBuoc');

-- ---------------------------------------------------------
-- 9. DON UNG TUYEN MOI
-- Tiep noi ID tu 8 den 20
-- ---------------------------------------------------------

INSERT INTO DonUngTuyen (MaDon, MaTin, MaUngVien, TenFile, DuongDanFile, DinhDang, NoiDungTrichXuat, TrangThai, NgayNop) VALUES
(8, 7, 28, 'CaoThang_Golang.pdf', '/cvs/caothang_go.pdf', 'PDF', 'Golang Developer. Chuyên làm hệ thống high concurrency. Redis, Docker, gRPC.', 'TrungTuyen', '2024-06-10 09:00'), -- Thang nop Go (Match cao)
(9, 7, 27, 'VuongDinh_PHP.pdf', '/cvs/vuongdinh_php.pdf', 'PDF', 'Backend Dev. 5 năm PHP, 4 năm sử dụng Laravel framework, MySQL optimization.', 'TuChoi', '2024-06-11 10:00'),    -- Dinh (PHP) nop Go (Fail)
(10, 8, 27, 'VuongDinh_PHP.pdf', '/cvs/vuongdinh_php.pdf', 'PDF', 'Backend Dev. 5 năm PHP, 4 năm sử dụng Laravel framework, MySQL optimization.', 'AIDaLoc', '2024-06-12 11:00'),   -- Dinh (PHP) nop PHP (Match cao)
(11, 9, 23, 'NguyenHa_Mobile.pdf', '/cvs/nguyenha_mobile.pdf', 'PDF', 'Mobile Developer. 4 năm Native Android (Kotlin), 2 năm cross-platform Flutter.', 'DaNop', '2024-06-13 14:00'),      -- Ha nop Flutter
(12, 10, 22, 'TranToan_QA.pdf', '/cvs/trantoan_qa.pdf', 'PDF', 'Automation QA. Sử dụng Selenium, Cypress. Có 3 năm kinh nghiệm test Web và Mobile app.', 'TrungTuyen', '2024-06-14 15:00'),-- Toan nop QA
(13, 11, 21, 'LeThanh_BA_CV.pdf', '/cvs/lethanh_ba.pdf', 'PDF', 'Business Analyst với 5 năm kinh nghiệm. Kỹ năng lấy requirements, vẽ UML, viết tài liệu. Có hiểu biết về SQL Server.', 'AIDaLoc', '2024-06-15 16:00'),   -- Thanh nop BA
(14, 12, 25, 'DoVan_DataEng.pdf', '/cvs/dovan_data.pdf', 'PDF', 'Data Engineer. Tech stack: Python, PostgreSQL, AWS Redshift, Airflow.', 'AIDaLoc', '2024-06-16 09:00'),  -- Van nop Data
(15, 13, 26, 'LyNhan_UIUX.pdf', '/cvs/lynhan_uiux.pdf', 'PDF', 'UI/UX Designer. Sử dụng thành thạo Figma, Adobe XD. Đã thiết kế app e-commerce.', 'DaNop', '2024-06-17 10:00'),    -- Nhan nop UI/UX
(16, 14, 29, 'DinhBao_Vue.pdf', '/cvs/dinhbao_vue.pdf', 'PDF', 'Frontend Dev 2 năm kinh nghiệm. Framework chính là VueJS, Vuex, NuxtJS.', 'AIDaLoc', '2024-06-18 11:00'),  -- Bao nop VueJS
(17, 14, 33, 'TuanAnh_MERN.pdf', '/cvs/tuananh_mern.pdf', 'PDF', 'MERN Stack. NodeJS, ReactJS, MongoDB. Có thể làm fullstack cho các dự án SME.', 'TuChoi', '2024-06-19 14:00'),   -- Tuan Anh (React) nop VueJS (Mismatch framework)
(18, 15, 24, 'PhamHung_iOS.docx', '/cvs/phamhung_ios.docx', 'DOCX', 'iOS Dev, 2 năm kinh nghiệm với Swift, UIKit, SwiftUI. Từng thử nghiệm React Native 1 dự án nhỏ.', 'TuChoi', '2024-05-20 15:00'),   -- Hung nop Fresher iOS nhung job da dong
(19, 12, 28, 'CaoThang_Golang.pdf', '/cvs/caothang_go.pdf', 'PDF', 'Golang Developer. Chuyên làm hệ thống high concurrency. Redis, Docker, gRPC.', 'TuChoi', '2024-06-20 09:00'),   -- Thang (Go) nop Data Engineer (Fail)
(20, 2, 33, 'TuanAnh_MERN.pdf', '/cvs/tuananh_mern.pdf', 'PDF', 'MERN Stack. NodeJS, ReactJS, MongoDB. Có thể làm fullstack cho các dự án SME.', 'DaNop', '2024-06-21 10:00');     -- Tuan Anh nop React (Job cu so 2)


-- ---------------------------------------------------------
-- 10. KET QUA AI PHAN TICH MOI
-- Tiep noi ID tu 8 den 20
-- ---------------------------------------------------------

INSERT INTO KetQua_AI (MaKetQua, MaDon, TrangThaiXuLy, DiemPhuHop, TomTatUngVien, KyNangPhuHop_Json, KyNangThieu_Json, DiemManh, DiemYeu, DeXuat) VALUES
(8, 8, 'HoanThanh', 95.00, 'Golang Developer 3 năm, phù hợp hệ thống high concurrency.', '["Golang", "Redis", "Docker"]', '[]', 'Nắm vững Redis', 'Chưa rõ kĩ năng Cloud', 'TuyenNhanh'),
(9, 9, 'HoanThanh', 20.00, 'Ứng viên làm PHP/Laravel, không có kỹ năng Golang.', '[]', '["Golang", "Redis"]', 'Kinh nghiệm backend lâu năm', 'Sai ngôn ngữ cốt lõi', 'LoaiBo'),
(10, 10, 'HoanThanh', 98.00, 'Ứng viên PHP/Laravel 5 năm, hoàn toàn đáp ứng công việc.', '["PHP", "Laravel", "MySQL"]', '[]', 'Dày dặn kinh nghiệm', 'Không có', 'TuyenNhanh'),
(11, 11, 'DangXuLy', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(12, 12, 'HoanThanh', 90.00, 'Automation QA tốt, mạnh về Selenium.', '["Selenium"]', '["Appium", "Java/Python"]', 'Kinh nghiệm test đa nền tảng', 'Thiếu Appium theo JD', 'TuyenNhanh'),
(13, 13, 'HoanThanh', 92.00, 'BA Senior, kỹ năng BA và UML xuất sắc.', '["Business Analysis", "UML", "SQL Server"]', '[]', 'Profile rất đẹp', 'Không có', 'TuyenNhanh'),
(14, 14, 'HoanThanh', 96.00, 'Data Engineer có kinh nghiệm AWS và Postgres.', '["Python", "PostgreSQL", "AWS"]', '[]', 'Tech stack hiện đại', 'Không', 'TuyenNhanh'),
(15, 15, 'DangXuLy', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(16, 16, 'HoanThanh', 85.00, 'Frontend VueJS đáp ứng đủ số năm kinh nghiệm.', '["VueJS", "JavaScript"]', '[]', 'Framework đúng JD', 'Chỉ mới 2 năm', 'CoTheCanNhac'),
(17, 17, 'HoanThanh', 40.00, 'Ứng viên chuyên ReactJS, không có kinh nghiệm VueJS.', '["JavaScript"]', '["VueJS"]', 'Biết JS', 'Sai Framework yêu cầu', 'LoaiBo'),
(18, 18, 'Loi', NULL, NULL, NULL, NULL, NULL, NULL, NULL), -- Loi xu ly AI hoac Job da dong
(19, 19, 'HoanThanh', 15.00, 'Ứng viên Backend Golang apply nhầm vị trí Data Engineer.', '[]', '["Python", "PostgreSQL", "AWS"]', 'Giỏi Go', 'Sai định hướng', 'LoaiBo'),
(20, 20, 'DangXuLy', NULL, NULL, NULL, NULL, NULL, NULL, NULL);


-- ---------------------------------------------------------
-- 11. MOCK LICH HEN PHONG VAN
INSERT INTO LichHenPhongVan (MaDon, NgayPhuongVan, GioPhuongVan, DiaDiem, LinkHop, HinhThuc, GhiChu, TrangThai) VALUES
(1, '2024-04-12', '09:00', 'Văn phòng FPT, Duy Tân', NULL, 'Offline', 'Phỏng vấn vòng 1 với Tech Lead', 'HoanThanh'),
(5, '2024-04-18', '14:00', NULL, 'https://zoom.us/j/123456789', 'Online', 'Phỏng vấn kỹ thuật trực tuyến', 'HoanThanh'),
(8, '2024-06-15', '10:00', 'Văn phòng Shopee, Liễu Giai', NULL, 'Offline', 'Gặp mặt trực tiếp Bộ phận Nhân sự', 'DaXacNhan'),
(12, '2024-06-20', '15:30', NULL, 'https://meet.google.com/abc-xyz', 'Online', 'Phỏng vấn với Project Manager', 'ChoXacNhan'),
(10, '2024-06-25', '09:00', 'Văn phòng VNPay, Láng Hạ', NULL, 'Offline', 'Phỏng vấn chuyên sâu kỹ thuật', 'ChoXacNhan');


-- Dong bo sequence IDENTITY sau khi INSERT ID tuong minh
-- Đồng bộ sequence IDENTITY sau khi INSERT ID tường minh.
-- Các identifier được viết thường vì PostgreSQL tự chuyển identifier
-- không có dấu ngoặc kép về chữ thường.
SELECT setval(pg_get_serial_sequence('vaitro', 'mavaitro'), COALESCE((SELECT MAX(mavaitro) FROM vaitro), 1), true);
SELECT setval(pg_get_serial_sequence('taikhoan', 'mataikhoan'), COALESCE((SELECT MAX(mataikhoan) FROM taikhoan), 1), true);
SELECT setval(pg_get_serial_sequence('danhmuckynang', 'makynang'), COALESCE((SELECT MAX(makynang) FROM danhmuckynang), 1), true);
SELECT setval(pg_get_serial_sequence('nganhnghe', 'manganhnghe'), COALESCE((SELECT MAX(manganhnghe) FROM nganhnghe), 1), true);
SELECT setval(pg_get_serial_sequence('tintuyendung', 'matin'), COALESCE((SELECT MAX(matin) FROM tintuyendung), 1), true);
SELECT setval(pg_get_serial_sequence('donungtuyen', 'madon'), COALESCE((SELECT MAX(madon) FROM donungtuyen), 1), true);
SELECT setval(pg_get_serial_sequence('ketqua_ai', 'maketqua'), COALESCE((SELECT MAX(maketqua) FROM ketqua_ai), 1), true);
SELECT setval(pg_get_serial_sequence('lichhenphongvan', 'malichhen'), COALESCE((SELECT MAX(malichhen) FROM lichhenphongvan), 1), true);


UPDATE NhaTuyenDung SET Logo = '/img/fpt.png' WHERE MaNhaTuyenDung = 3;
UPDATE NhaTuyenDung SET Logo = '/img/vng.png' WHERE MaNhaTuyenDung = 4;
UPDATE NhaTuyenDung SET Logo = '/img/viettel.png' WHERE MaNhaTuyenDung = 5;
UPDATE NhaTuyenDung SET Logo = '/img/momo.png' WHERE MaNhaTuyenDung = 6;

SELECT * FROM TaiKhoan;
SELECT * FROM UngVien;
SELECT * FROM NhaTuyenDung;
SELECT * FROM TinTuyenDung;
SELECT * FROM ChiTietKyNang_TinTuyenDung;
SELECT * FROM ChiTietKyNang_UngVien;
SELECT * FROM DanhMucKyNang;
SELECT * FROM DonUngTuyen;
SELECT * FROM KetQua_AI;
SELECT * FROM LichHenPhongVan;
SELECT * FROM NganhNghe